import type { ContentPack } from './registry';

const unsplash = (id: string, w = 1600, h = 1100) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;

export const GROUP_5: Record<string, ContentPack> = {
  pizzaria: {
    slug: 'pizzaria',
    tagline: 'Pizza napolitana feita como em Nápoles — fermentação de 72h, forno a 480°C.',
    palette: { primary: '#1a0a05', secondary: '#9a3412', accent: '#ea580c', surface: '#fff7ed' },
    hero: {
      eyebrow: 'Napolitana · Forno a lenha · 72h de fermentação',
      title: 'A pizza napolitana como ela deve ser.',
      subtitle: 'Forno Stefano Ferrara a 480°C, farinha Tipo 00 da Campânia, fermentação de 72 horas e ingredientes DOP. Sete sabores clássicos, um tartufo.',
      ctaLabel: 'Reservar mesa',
      ctaHref: '#contato',
      image: unsplash('1513104890138-7c749659a591'),
    },
    aboutText:
      'Pizzaria certificada pela Associazione Verace Pizza Napoletana desde 2019. Oito pizzaiolos napolitanos na cozinha, farinha importada e mozzarella di bufala DOP entregue semanalmente de Nápoles. Aceitamos a fila — desde que valha a espera.',
    services: [
      { icon: '🍕', name: 'Pizzas clássicas', desc: 'Margherita DOP, Marinara, Quattro Formaggi e mais cinco receitas tradicionais.' },
      { icon: '🔥', name: 'Forno a lenha', desc: 'Stefano Ferrara, da Campânia. A 480°C, em 90 segundos a pizza está pronta.' },
      { icon: '🌿', name: 'Ingredientes DOP', desc: 'Mozzarella di bufala, San Marzano, azeite extra virgem toscano.' },
      { icon: '🍷', name: 'Vinhos italianos', desc: 'Carta com 84 rótulos, em sua maioria da Toscana e do Piemonte.' },
      { icon: '🛵', name: 'Delivery aquecido', desc: 'Pizzas em bolsa térmica, chegam em 35 min ainda fumegando.' },
      { icon: '🎂', name: 'Eventos', desc: 'Pizza party para até 60 pessoas, com pizzaiolo ao vivo na sua casa.' },
    ],
    differentials: [
      { name: 'Certificada AVPN', desc: 'Siga as regras da Associazione Verace Pizza Napoletana.' },
      { name: 'Farinha Tipo 00', desc: 'Importada da Campânia, moinho Molino Quaglia.' },
      { name: 'Sem fila com reserva', desc: 'Reserva online garantida, sem espera no balcão.' },
    ],
    stats: [
      { value: '84 rótulos', label: 'de vinhos italianos' },
      { value: '7 anos', label: 'de certificação AVPN' },
      { value: '1.200g', label: 'de massa por pizza' },
      { value: '90 seg', label: 'no forno a 480°C' },
    ],
    menu: [
      { name: 'Margherita DOP', price: 'R$ 88' },
      { name: 'Marinara', price: 'R$ 76' },
      { name: 'Quattro Formaggi', price: 'R$ 102' },
      { name: 'Diavola', price: 'R$ 96' },
      { name: 'Prosciutto e Rúcula', price: 'R$ 110' },
      { name: 'Tartufo Nero (trufa negra)', price: 'R$ 168' },
    ],
    testimonials: [
      { name: 'Família Bertelli', role: 'Clientes desde 2020', text: 'A gente vinha para São Paulo todo mês só para comer essa pizza. Agora moramos aqui.' },
      { name: 'Carlo Mancini', role: 'Chef, Ristorante Milano', text: 'A melhor Margherita que comi fora da Itália. Ponto exato da massa, molho vibrante.' },
    ],
    faq: [
      { q: 'Vocês entregam em quais bairros?', a: 'Raio de 6 km. Para regiões mais distantes, congelamos a pizza crua e você finaliza em casa no forno.' },
      { q: 'É possível fazer pizza sem glúten?', a: 'Sim, com massa de fermentação natural à base de arroz e polvilho. +R$ 18.' },
      { q: 'Aceitam reserva para grupos grandes?', a: 'Sim, até 24 pessoas no salão. Para grupos maiores, evento fechado com pizzaiolo ao vivo.' },
    ],
    ctaTitle: 'Reserve sua mesa hoje',
    ctaLabel: 'Reservar agora',
    whatsapp: '5511988007070',
    phone: '(11) 3061-7070',
    email: 'reservas@pizzarianapolitana.com.br',
    address: 'Rua Augusta, 2450 — Cerqueira César, São Paulo/SP',
    hours: 'Ter–Dom, 18h–00h · Fechado seg',
    cnpj: '34.521.987/0001-12',
    instagram: 'https://instagram.com/pizzarianapolitana',
  },

  padaria: {
    slug: 'padaria',
    tagline: 'Padaria artesanal de fermentação natural — pão, bolo e café que têm dono.',
    palette: { primary: '#451a03', secondary: '#a16207', accent: '#d97706', surface: '#fefce8' },
    hero: {
      eyebrow: 'Fermentação natural 36h · Farinha orgânica · Café especial',
      title: 'O pão que sua avó reconheceria.',
      subtitle: 'Mestre padeiro formado na École Lenôtre, fermento natural cultivado há 8 anos, farinhas de moinho certificado. A padaria do bairro que virou ponto de encontro.',
      ctaLabel: 'Ver cardápio',
      ctaHref: '#cardapio',
      image: unsplash('1517433367423-c7e5b0f35086'),
    },
    aboutText:
      'Três sócios abriram a padaria em 2017 para resgatar o pão de fermentação natural que estava sumindo de São Paulo. Hoje atendemos 1.400 clientes por dia, vendemos 22 tipos de pão, 18 variedades de bolo e torramos microlotes de café especial na casa.',
    services: [
      { icon: '🥖', name: 'Pães de fermentação natural', desc: 'Baguete, cacetinho, integral, centeio, brioche, focaccia. 22 tipos.' },
      { icon: '☕', name: 'Café especial', desc: 'Microlotes brasileiros pontuados acima de 86 SCA, torrados na casa.' },
      { icon: '🎂', name: 'Bolos sob encomenda', desc: 'Tradicionais, sem açúcar, integrais e veganos. Encomendas com 48h.' },
      { icon: '🥐', name: 'Confeitaria francesa', desc: 'Croissant, pain au chocolat, brioche, éclair. Produzidos 4x por dia.' },
      { icon: '🛵', name: 'Delivery', desc: 'Raio de 4 km. Pão chega ainda morno, em embalagem de juta.' },
      { icon: '👨‍🍳', name: 'Curso de panificação', desc: 'Turmas mensais, 4 sábados, 16 alunos. Próxima: 09 de setembro.' },
    ],
    differentials: [
      { name: 'Farinha orgânica', desc: 'Moinho Globo, certificada IBD. Trigo rastreado da fazenda.' },
      { name: 'Fermento de 8 anos', desc: 'Levain mãe cultivado desde 2017. A gente conhece cada bactéria dele.' },
      { name: 'Sem conservantes', desc: 'Produção diária, congelamento zero. O que sobrou vira pudim no dia seguinte.' },
    ],
    stats: [
      { value: '22', label: 'tipos de pão' },
      { value: '18', label: 'variedades de bolo' },
      { value: '1.400', label: 'clientes por dia' },
      { value: '8 anos', label: 'de fermento natural' },
    ],
    menu: [
      { name: 'Pão de fermentação natural (1 kg)', price: 'R$ 42' },
      { name: 'Brioche (un)', price: 'R$ 14' },
      { name: 'Croissant de amêndoas', price: 'R$ 16' },
      { name: 'Bolo de cenoura com cobertura (fatia)', price: 'R$ 13' },
      { name: 'Café coado 200ml (microlote)', price: 'R$ 11' },
      { name: 'Torta de frango (inteira)', price: 'R$ 95' },
    ],
    testimonials: [
      { name: 'Sônia Padilha', role: 'Moradora do bairro', text: 'Vou todo sábado das 7h às 8h. Café, croissant e bate-papo. Não troco por brunch paulistano nenhum.' },
      { name: 'Bruno Tanaka', role: 'Chef, Kosmik', text: 'O levain deles é referência. Já pedi conselho sobre fermento com o mestre, e ele deu com prazer.' },
    ],
    faq: [
      { q: 'Vocês fazem pão sem glúten?', a: 'Sim, às quartas e sextas. Encomenda com 24h.' },
      { q: 'Como funcionam os cursos?', a: 'Turmas de 16 alunos, 4 sábados seguidos, das 8h ao meio-dia. R$ 1.480, inclui apostila e certificado.' },
      { q: 'Atendem cafés para escritório?', a: 'Sim, contrato mensal. A partir de R$ 22 por colaborador/dia, com entrega às 8h30.' },
    ],
    ctaTitle: 'Pão quentinho das 7h às 20h',
    ctaLabel: 'Pedir agora',
    whatsapp: '5511977008080',
    phone: '(11) 3061-8080',
    email: 'oi@padariaferreira.com.br',
    address: 'Rua Joaquim Antunes, 180 — Pinheiros, São Paulo/SP',
    hours: 'Seg–Sáb, 7h–20h · Dom, 8h–14h',
    cnpj: '28.654.321/0001-44',
    instagram: 'https://instagram.com/padariaferreira',
  },

  academia: {
    slug: 'academia',
    tagline: 'Academia de 1.800 m² onde a regra é uma: resultado em 90 dias, com gente de verdade.',
    palette: { primary: '#052e16', secondary: '#15803d', accent: '#22c55e', surface: '#f0fdf4' },
    hero: {
      eyebrow: 'Musculação · Cross · Pilates · Yoga · Spinning',
      title: 'Treinar sem plateia, com gente que te conhece.',
      subtitle: 'Equipamentos Hammer Strength e Technogym, 88 aulas por semana, 22 educadores físicos. Aqui você não é mais um número da planilha — é aluno do professor.',
      ctaLabel: 'Aula experimental grátis',
      ctaHref: '#contato',
      image: unsplash('1534438327276-14e5300c3a48'),
    },
    aboutText:
      'Fundada em 2014, somos uma academia independente — sem franquia, sem venda casada. 1.800 m² no Itaim com musculação, cross training, pilates, yoga, spinning, judô e área de cardio. 2.400 alunos ativos, 78% renovam a cada 12 meses.',
    services: [
      { icon: '🏋️', name: 'Musculação', desc: 'Equipamentos Hammer Strength, Technogym e Cybex. Espaço de 600 m².' },
      { icon: '🔥', name: 'Cross training', desc: 'Box dedicado, aulas de 1h com coach. 22 vagas por turma.' },
      { icon: '🧘', name: 'Pilates e yoga', desc: 'Salas equipadas, instrutores formados, aulas de 50 minutos.' },
      { icon: '🚴', name: 'Spinning', desc: 'Bikes Stages, aulas com batida e iluminação. 18 lugares por turma.' },
      { icon: '🥗', name: 'Nutrição esportiva', desc: 'Consultoria mensal com nutricionista, R$ 220/mês avulso.' },
      { icon: '🧑‍⚕️', name: 'Avaliação física', desc: 'Composição corporal por bioimpedância InBody 770. Inclusa na mensalidade.' },
    ],
    differentials: [
      { name: 'Sem fidelidade', desc: 'Cancela quando quiser, sem multa. A gente ganha você todo mês.' },
      { name: 'Aula experimental grátis', desc: 'Para novos alunos, sem compromisso. Acompanhado de educador físico.' },
      { name: 'Educadores sempre presentes', desc: 'Não é self-service. Sempre tem professor no salão te orientando.' },
    ],
    stats: [
      { value: '2.400', label: 'alunos ativos' },
      { value: '88', label: 'aulas por semana' },
      { value: '78%', label: 'renovam em 12 meses' },
      { value: '22', label: 'profissionais de educação física' },
    ],
    testimonials: [
      { name: 'Renata Duarte', role: 'Aluna há 3 anos', text: 'Já fui de 4 academias. Aqui o educador me conhece pelo nome, sabe do meu joelho, e cobra quando eu não apareço.' },
      { name: 'Marcos Hayashi', role: 'Atleta amador', text: 'A estrutura de cross é uma das melhores de SP. A programação muda toda segunda, nunca fica chato.' },
    ],
    faq: [
      { q: 'Posso treinar todos os dias?', a: 'Sim, musculação e aulas são abertas. Para cross, agende os slots com antecedência.' },
      { q: 'A mensalidade inclui personal?', a: 'Não, mas a primeira aula com personal é cortesia. Depois, pacotes a partir de R$ 280/mês.' },
      { q: 'Aceitam convênio?', a: 'Trabalhamos com TotalPass, Gympass e Wellhub. Confira a cobertura do seu plano.' },
    ],
    ctaTitle: 'Aula experimental sem custo',
    ctaLabel: 'Agendar agora',
    whatsapp: '5511988009090',
    phone: '(11) 4008-9090',
    email: 'contato@academia.treino.com.br',
    address: 'Av. Brigadeiro Faria Lima, 5500 — Itaim Bibi, São Paulo/SP',
    hours: 'Seg–Sex, 5h–23h · Sáb/Dom, 7h–18h',
    cnpj: '42.369.852/0001-78',
    instagram: 'https://instagram.com/academiatreino',
  },

  'pet-shop': {
    slug: 'pet-shop',
    tagline: 'Banho, tosa, veterinária 24h e a maior loja de bairro da região.',
    palette: { primary: '#3f1d0a', secondary: '#b45309', accent: '#f59e0b', surface: '#fffbeb' },
    hero: {
      eyebrow: 'Banho · Tosa · Veterinária 24h · Loja',
      title: 'Cuidar de pet é coisa séria — a gente trata como tal.',
      subtitle: '18 veterinários com CRMV ativo, 22 banhadores formados, internação 24h, centro cirúrgico e 4.200 itens na loja. Seu pet é nosso paciente, não nosso cliente.',
      ctaLabel: 'Agendar banho ou consulta',
      ctaHref: '#contato',
      image: unsplash('1548199973-03cce0bbc87b'),
    },
    aboutText:
      'Fundado em 2016 por uma médica-veterinária cansada de ver superlotação em pet shops comuns. Hoje somos referência em três bairros: temos veterinária 24h com internação, centro cirúrgico, banho e tosa com agendamento online, e a maior loja do entorno com 4.200 SKUs.',
    services: [
      { icon: '🛁', name: 'Banho e tosa', desc: 'Pacotes a partir de R$ 48. Banho medicinal para pets com dermatite, +R$ 30.' },
      { icon: '🩺', name: 'Veterinária 24h', desc: 'Pronto-socorro, consultas, internação, exames de imagem e laboratório.' },
      { icon: '💉', name: 'Vacinação', desc: 'Calendário completo, com carteirinha digital e lembretes por WhatsApp.' },
      { icon: '✂️', name: 'Tosa específica por raça', desc: 'Yorkshire, Shih Tzu, Poodle, Golden, Schnauzer — tosadores especialistas.' },
      { icon: '🛍️', name: 'Loja', desc: '4.200 itens: ração super premium, brinquedos Kong, medicamentos, antipulgas.' },
      { icon: '🏠', name: 'Hospedagem', desc: 'Espaço monitorado 24h, câmera individual, áreas separadas por porte e idade.' },
    ],
    differentials: [
      { name: 'Veterinária 24h de verdade', desc: 'Médico no local, não é só telefone. Pronto-socorro funciona em todos os feriados.' },
      { name: 'Equipe com CRMV ativo', desc: 'A gente exibe o número de registro. Se quiser conferir no conselho, pode.' },
      { name: 'Agendamento online', desc: 'Sem fila de espera, com confirmação por SMS e WhatsApp.' },
    ],
    stats: [
      { value: '18', label: 'veterinários' },
      { value: '22', label: 'banhadores formados' },
      { value: '4.200', label: 'itens na loja' },
      { value: '24/7', label: 'veterinária no local' },
    ],
    testimonials: [
      { name: 'Luciana Seixas', role: 'Tutora do Bob (Golden)', text: 'O Bob teve uma torção às 23h de um domingo. A veterinária atendeu, examinou, medicou — salvou o joelho dele.' },
      { name: 'Roberto e Cláudia', role: 'Tutores do Thor e da Luna', text: 'A gente confia nossos dois como se fosse família da família. Tosa, banho, ração, tudo ali.' },
    ],
    faq: [
      { q: 'Atendem emergência à noite?', a: 'Sim, veterinária 24h, inclusive feriados. Não é só telefone — o médico está no local.' },
      { q: 'Quanto custa banho para um Golden?', a: 'Banho padrão R$ 78. Com hidratação, R$ 98. Tosa na máquina, R$ 110.' },
      { q: 'Vendem ração por delivery?', a: 'Sim, raio de 8 km. Frete grátis acima de R$ 150. Pedidos pelo WhatsApp.' },
    ],
    ctaTitle: 'Agende banho ou consulta',
    ctaLabel: 'Agendar agora',
    whatsapp: '5511988010101',
    phone: '(11) 4009-1010',
    email: 'agendamento@petcenter.com.br',
    address: 'Rua Cotoxó, 1100 — Pompeia, São Paulo/SP',
    hours: 'Loja: Seg–Sáb, 8h–22h · Dom, 9h–18h · Vet 24h',
    cnpj: '38.741.256/0001-90',
    instagram: 'https://instagram.com/petcenter',
  },

  fotografo: {
    slug: 'fotografo',
    tagline: 'Casamentos, eventos e ensaios autorais — a foto que sua família vai olhar daqui a 30 anos.',
    palette: { primary: '#0a0a0a', secondary: '#334155', accent: '#0f172a', surface: '#f8fafc' },
    hero: {
      eyebrow: 'Casamentos · Eventos · Ensaios autorais',
      title: 'A fotografia que emociona antes de decorar.',
      subtitle: 'Mais de 240 casamentos fotografados, 18 anos de carreira, equipamento profissional full-frame. Sua história merece um fotógrafo que enxerga além do enquadramento.',
      ctaLabel: 'Reservar data',
      ctaHref: '#contato',
      image: unsplash('1606216794074-735e91aa2c92'),
    },
    aboutText:
      'Estúdio fundado por Helena Moraes em 2008. Hoje somos 8 fotógrafos assistentes, 2 cinegrafistas, equipe de produção e edição em até 30 dias. Já publicamos em Casamentos Brasil, Noivas em Foco e Vogue Noivas. Atendemos São Paulo, Rio, litoral e destino internacional.',
    services: [
      { icon: '💍', name: 'Casamentos', desc: 'Cobertura completa, making of, álbum fine art e slideshow.' },
      { icon: '🎂', name: 'Aniversários e eventos', desc: 'Cobertura de 4h a 10h, fotos e vídeo, entrega em 15 dias.' },
      { icon: '👶', name: 'Ensaio newborn', desc: 'Estúdio preparado, sessão de 2h, 40 fotos editadas.' },
      { icon: '👰', name: 'Ensaio pré-wedding', desc: 'Locação externa ou estúdio, 1h30, 60 fotos editadas.' },
      { icon: '🏢', name: 'Eventos corporativos', desc: 'Cobertura discreta, fotojornalismo e retrato executivo.' },
      { icon: '📸', name: 'Ensaios autorais', desc: 'Para artistas, marcas e pessoas. Direção criativa e produção.' },
    ],
    differentials: [
      { name: 'Entrega em 30 dias', desc: 'Galeria online + fotos editadas. Casamentos: 60 dias, com prévia em 15.' },
      { name: 'Backup em 3 locais', desc: 'HDD, nuvem criptografada e estúdio. Suas fotos não se perdem.' },
      { name: 'Equipamento pro', desc: 'Sony A7R V, iluminação Aputure, drones DJI Mavic 3 Pro.' },
    ],
    stats: [
      { value: '240+', label: 'casamentos fotografados' },
      { value: '18 anos', label: 'de carreira' },
      { value: '30 dias', label: 'prazo de entrega' },
      { value: '10 pessoas', label: 'no time' },
    ],
    gallery: [
      { src: unsplash('1519741497674-611481863552', 700, 700) },
      { src: unsplash('1465495976277-4387d4b0b4c6', 700, 700) },
      { src: unsplash('1511285560929-80b456fea0bc', 700, 700) },
      { src: unsplash('1606800052052-a08af7148866', 700, 700) },
      { src: unsplash('1606216794074-735e91aa2c92', 700, 700) },
      { src: unsplash('1606490194859-07c18c9f0968', 700, 700) },
    ],
    testimonials: [
      { name: 'Marina e Felipe', role: 'Casaram em 2024', text: 'A Helena não tirou foto — contou a história. Cada álbum que abrimos, lembramos de uma coisa nova.' },
      { name: 'Família Coelho', role: 'Ensaio newborn 2025', text: 'Profissionalismo raro, do primeiro WhatsApp à entrega. As fotos do Bento estão expostas na nossa sala.' },
    ],
    faq: [
      { q: 'Quanto custa um casamento?', a: 'Pacote completo a partir de R$ 8.500 (8h de cobertura, 2 fotógrafos, álbum 30x30, making of).' },
      { q: 'Vocês viajam?', a: 'Sim. Casamentos em destino têm acréscimo de deslocamento e diárias. Atendemos Brasil e exterior.' },
      { q: 'Posso parcelar?', a: 'Em até 6x no cartão ou contrato personalizado em até 12x. Sinal de 30% na reserva da data.' },
    ],
    ctaTitle: 'Reservar data do seu casamento',
    ctaLabel: 'Reservar agora',
    whatsapp: '5511988011111',
    phone: '(11) 3068-1111',
    email: 'contato@helenafotografia.com.br',
    address: 'Estúdio Vila Madalena, São Paulo/SP',
    hours: 'Atendimento seg–sex, 9h–19h · Sáb sob agendamento',
    cnpj: '31.456.789/0001-65',
    instagram: 'https://instagram.com/helenafotografia',
  },
};
